# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bela.io
description: >- # this means to ignore newlines until "baseurl:"
  This is the main site for Bela.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

socials:
  - twitter: belaPlatform
  - github:  belaPlatform
  - facebook: belaPlatform
  - youtube: belaPlatform

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Tell Jekyll where the sass files are. These are in a top-level directory called _sass:
sass:
    sass_dir: _sass

# These are post categories.
# NEWS: Items, usually newsletter stuff, that shows up on front page
# EVENTS: Show up on the NEWS page, but not on the front page
# PROJECTS: Selected projects that are in the portfolio

categories:
  - news
  - events
  - projects


exclude: 
  - node_modules

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
